services:
  nextjs_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/ping']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    container_name: nginx_prod
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro,z
    depends_on:
      nextjs_app:
        condition: service_healthy
    networks:
      - appnet

networks:
  appnet:
