import { CinzelFont, LoraFont, OZWizard } from '@/lib/font';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '500 - Internal Server Error',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${OZWizard.variable} ${LoraFont.variable} ${CinzelFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
